# Generated by Django 5.1.5 on 2025-01-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='生産者名')),
            ],
        ),
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='騎手名')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(verbose_name='項')),
                ('race_id', models.CharField(max_length=20, unique=True, verbose_name='レースID')),
                ('race_name', models.CharField(max_length=100, verbose_name='レース名')),
                ('distance', models.IntegerField(verbose_name='距離')),
                ('weather', models.CharField(max_length=50, verbose_name='天候')),
                ('track_condition', models.CharField(max_length=50, verbose_name='馬場')),
                ('year', models.IntegerField(verbose_name='開催年')),
                ('course', models.CharField(max_length=100, verbose_name='開催コース')),
                ('race_number', models.IntegerField(verbose_name='開催回')),
                ('date', models.DateField(verbose_name='開催日')),
                ('race_type', models.CharField(max_length=50, verbose_name='レース')),
                ('no', models.IntegerField(verbose_name='No')),
            ],
        ),
        migrations.CreateModel(
            name='RaceHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField(unique=True)),
                ('html_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='調教師名')),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(verbose_name='項')),
                ('name', models.CharField(max_length=100, verbose_name='馬名')),
                ('sex_age', models.CharField(max_length=10, verbose_name='性齢')),
                ('birth_date', models.DateField(verbose_name='生産年月')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='セリ取引価格')),
                ('sire', models.CharField(max_length=100, verbose_name='父')),
                ('dam', models.CharField(max_length=100, verbose_name='母')),
                ('damsire', models.CharField(max_length=100, verbose_name='母父')),
                ('breeder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_1.breeder', verbose_name='生産者')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_1.trainer', verbose_name='調教師')),
            ],
        ),
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(verbose_name='項')),
                ('sire', models.CharField(max_length=100, verbose_name='父')),
                ('dam', models.CharField(max_length=100, verbose_name='母')),
                ('damsire', models.CharField(max_length=100, verbose_name='母父')),
                ('horse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree', to='App_1.horse', verbose_name='競走馬')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(verbose_name='項')),
                ('category', models.CharField(max_length=50, verbose_name='項目')),
                ('horse_gate', models.IntegerField(verbose_name='馬枠')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金額')),
                ('popularity', models.IntegerField(blank=True, null=True, verbose_name='人気')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='App_1.race', verbose_name='レース')),
            ],
        ),
        migrations.CreateModel(
            name='LapTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(verbose_name='項')),
                ('category', models.CharField(max_length=50, verbose_name='項目')),
                ('m200', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='200m')),
                ('m400', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='400m')),
                ('m600', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='600m')),
                ('m800', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='800m')),
                ('m1000', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='1000m')),
                ('m1200', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='1200m')),
                ('m1400', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='1400m')),
                ('m1600', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='1600m')),
                ('m1800', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='1800m')),
                ('m2000', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='2000m')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_times', to='App_1.race', verbose_name='レース')),
            ],
        ),
        migrations.CreateModel(
            name='CornerPassageRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(verbose_name='項')),
                ('corner', models.CharField(max_length=50, verbose_name='コーナー')),
                ('passage_order', models.IntegerField(verbose_name='通過順位')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corner_passages', to='App_1.race', verbose_name='レース')),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(verbose_name='項')),
                ('position', models.IntegerField(verbose_name='着順')),
                ('gate', models.IntegerField(verbose_name='枠')),
                ('horse_number', models.IntegerField(verbose_name='馬番')),
                ('sex_age', models.CharField(max_length=10, verbose_name='性齢')),
                ('weight_carried', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='斤量')),
                ('time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='タイム')),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='着差')),
                ('popularity', models.IntegerField(blank=True, null=True, verbose_name='人気')),
                ('odds_win', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='単勝オッズ')),
                ('last3f', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='後3F')),
                ('corner_passage_order', models.IntegerField(blank=True, null=True, verbose_name='コーナー通過順')),
                ('body_weight_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='馬体重(増減)')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='App_1.horse', verbose_name='馬')),
                ('jockey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_1.jockey', verbose_name='騎手')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='App_1.race', verbose_name='レース')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_1.trainer', verbose_name='厩舎')),
            ],
        ),
        migrations.CreateModel(
            name='RaceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(verbose_name='項')),
                ('gate', models.IntegerField(verbose_name='枠')),
                ('horse_number', models.IntegerField(verbose_name='馬番')),
                ('weight_carried', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='斤量')),
                ('body_weight_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='馬体重(増減)')),
                ('odds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='オッズ（更新）')),
                ('popularity', models.IntegerField(blank=True, null=True, verbose_name='人気')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='App_1.horse', verbose_name='馬')),
                ('jockey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_1.jockey', verbose_name='騎手')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='App_1.race', verbose_name='レース')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_1.trainer', verbose_name='厩舎')),
            ],
        ),
    ]
