# Generated by Django 5.1.5 on 2025-01-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='item',
            field=models.IntegerField(blank=True, verbose_name='項'),
        ),
    ]
