# Generated by Django 5.1.5 on 2025-01-22 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0004_alter_jockey_name_alter_race_course_alter_race_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生産年月'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_1.breeder', verbose_name='生産者'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='dam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='母'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='damsire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='母父'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='item',
            field=models.IntegerField(blank=True, null=True, verbose_name='項'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='sex_age',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='性齢'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='sire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='父'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_1.trainer', verbose_name='調教師'),
        ),
    ]
