# Generated by Django 5.1.5 on 2025-01-22 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0005_alter_horse_birth_date_alter_horse_breeder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceentry',
            name='gate',
            field=models.IntegerField(blank=True, null=True, verbose_name='枠'),
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='horse_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='馬番'),
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='item',
            field=models.IntegerField(blank=True, null=True, verbose_name='項'),
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_1.trainer', verbose_name='厩舎'),
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='weight_carried',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='斤量'),
        ),
        migrations.DeleteModel(
            name='RaceResult',
        ),
    ]
