# Generated by Django 5.1.5 on 2025-01-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0007_alter_race_race_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cornerpassagerank',
            name='corner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='コーナー'),
        ),
        migrations.AlterField(
            model_name='cornerpassagerank',
            name='item',
            field=models.IntegerField(blank=True, null=True, verbose_name='項'),
        ),
        migrations.AlterField(
            model_name='cornerpassagerank',
            name='passage_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='通過順位'),
        ),
        migrations.AlterField(
            model_name='laptime',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='項目'),
        ),
        migrations.AlterField(
            model_name='laptime',
            name='item',
            field=models.IntegerField(blank=True, null=True, verbose_name='項'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='項目'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='horse_gate',
            field=models.IntegerField(blank=True, null=True, verbose_name='馬枠'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='item',
            field=models.IntegerField(blank=True, null=True, verbose_name='項'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='dam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='母'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='damsire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='母父'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='item',
            field=models.IntegerField(blank=True, null=True, verbose_name='項'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='sire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='父'),
        ),
        migrations.AlterField(
            model_name='racehtml',
            name='html_text',
            field=models.TextField(blank=True, null=True, verbose_name='HTMLテキスト'),
        ),
        migrations.AlterField(
            model_name='racehtml',
            name='race_id',
            field=models.IntegerField(unique=True, verbose_name='レースID'),
        ),
    ]
