# Generated by Django 5.1.5 on 2025-01-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0009_alter_payout_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='金額'),
        ),
    ]
