# Generated by Django 5.1.5 on 2025-01-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0010_alter_payout_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raceentry',
            old_name='item',
            new_name='OrderOfFinish',
        ),
    ]
