# Generated by Django 5.1.5 on 2025-01-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0011_rename_item_raceentry_orderoffinish'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptime',
            name='m2200',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='2200m'),
        ),
        migrations.AddField(
            model_name='laptime',
            name='m2400',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='2400m'),
        ),
        migrations.AddField(
            model_name='laptime',
            name='m2600',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='2600m'),
        ),
        migrations.AddField(
            model_name='laptime',
            name='m2800',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='2800m'),
        ),
        migrations.AddField(
            model_name='laptime',
            name='m3000',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='3000m'),
        ),
        migrations.AddField(
            model_name='laptime',
            name='m3200',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='3200m'),
        ),
        migrations.AddField(
            model_name='laptime',
            name='m3400',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='3400m'),
        ),
    ]
