# Generated by Django 5.1.5 on 2025-01-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0012_laptime_m2200_laptime_m2400_laptime_m2600_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=30, null=True, verbose_name='金額'),
        ),
    ]
