# Generated by Django 5.1.5 on 2025-01-30 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0014_remove_raceentry_orderoffinish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='馬主名')),
                ('owner_netkeiba_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='馬主netkeibaID')),
            ],
        ),
        migrations.AddField(
            model_name='horse',
            name='horse_netkeiba_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='馬netkeibaID'),
        ),
        migrations.AddField(
            model_name='jockey',
            name='jockey_netkeiba_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='騎手netkeibaID'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_netkeiba_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='調教師netkeibaID'),
        ),
        migrations.AddField(
            model_name='raceentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_1.owner', verbose_name='馬主'),
        ),
    ]
