# Generated by Django 5.1.5 on 2025-02-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0015_owner_horse_horse_netkeiba_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='グレード'),
        ),
    ]
