# Generated by Django 5.1.5 on 2025-02-25 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0016_race_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racehtml',
            name='race_id',
        ),
        migrations.AddField(
            model_name='racehtml',
            name='race',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='racehtml', to='App_1.race', verbose_name='レース'),
        ),
        migrations.AddField(
            model_name='racehtml',
            name='raceid',
            field=models.IntegerField(default='202501010101', unique=True, verbose_name='レースID'),
        ),
    ]
