# Generated by Django 5.1.5 on 2025-02-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0017_remove_racehtml_race_id_racehtml_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racehtml',
            name='raceid',
            field=models.IntegerField(default=202501010101, unique=True, verbose_name='レースID'),
        ),
    ]
