# Generated by Django 5.1.5 on 2025-02-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0018_alter_racehtml_raceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racehtml',
            name='raceid',
            field=models.IntegerField(default=None, null=True, unique=True, verbose_name='レースID'),
        ),
    ]
