# Generated by Django 5.1.5 on 2025-02-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0019_alter_racehtml_raceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racehtml',
            name='race',
        ),
        migrations.RemoveField(
            model_name='racehtml',
            name='raceid',
        ),
    ]
